version: "3.8"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:80
    restart: on-failure
    networks:
      - network_app

  backend:
    container_name: backend
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/content/dictionary.txt:/app/content/dictionary.txt
    ports:
      - 8000:8000
    restart: on-failure
    networks:
      - network_app

networks:
  network_app:
